### ISSUE TITLE
git push should update origin/master

### ISSUE THREAD

**Issue by pchampin** [onlywei/explain-git-with-d3#50] opened 2016-11-09 11:24 UTC
try the following:
```
git commit
git fetch
git merge origin/master
git push
```
after the push, the branch `origin/master` has not been updated from its position got after the fetch, which is not consistent with how git actually works (it should end up on the same commit as master).

**Comment by kheyse-oqton** [comment] 2018-03-02 09:59
Seems to work for me.

**Comment by kheyse-oqton** [comment] 2018-03-02 10:13
Duplicate of #19 ?

**Comment by pchampin** [comment] 2018-03-02 12:14
Indeed, it is a duplicate.

**Comment by waldyrious** [comment] 2018-03-02 18:43
> Indeed, it is a duplicate.

Any reason not to close this, then?

**Closed** 2018-03-02 21:49 UTC
